import type { Metadata } from "next";
import "./globals.css";
import NavBarSection from "./components/NavBarSection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {/* <Navbar/> */}
        <NavBarSection/>
        {children}
      </body>
    </html>
  );
}
